variables:
  GIT_STRATEGY: none
  GIT_CHECKOUT: "false"

stages:
  - build
  - code-analysis
  - deploy

dev-build:
  stage: build
  tags:
    - devenv
  only:
    - dev
  script:
    - trigger -h http://gitlab.fpt.net -u /api/v4/projects -a rd6ApchjALgm-d7uzkCA -p deb638fe6d902c968a4e8ca443ca60 -o 0 -e STAGE="build" -e DOCKER_TAG=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA -t dev 2628
dev-code-analysis:
  stage: code-analysis
  tags:
    - devenv
  only:
    - dev
  script:
    - trigger -h http://gitlab.fpt.net -u /api/v4/projects -a rd6ApchjALgm-d7uzkCA -p deb638fe6d902c968a4e8ca443ca60 -o 1 -e STAGE="code-analysis" -e DOCKER_TAG=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA -t dev 2628
dev-deploy:
  stage: deploy
  tags:
    - devenv
  only:
    - dev
  script:
    - trigger -h http://gitlab.fpt.net -u /api/v4/projects -a rd6ApchjALgm-d7uzkCA -p deb638fe6d902c968a4e8ca443ca60 -e STAGE="deploy" -e DOCKER_TAG=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA -t dev 2628

stg-build:
  stage: build
  tags:
    - devenv
  only:
    - staging
  script:
    - trigger -h http://gitlab.fpt.net -u /api/v4/projects -a rd6ApchjALgm-d7uzkCA -p deb638fe6d902c968a4e8ca443ca60 -o 0 -e STAGE="build" -e DOCKER_TAG=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA -t staging 2628
stg-deploy:
  stage: deploy
  tags:
    - devenv
  only:
    - staging
  script:
    - trigger -h http://gitlab.fpt.net -u /api/v4/projects -a rd6ApchjALgm-d7uzkCA -p deb638fe6d902c968a4e8ca443ca60 -e STAGE="deploy" -e DOCKER_TAG=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA -t staging 2628

prod-build:
  stage: build
  tags:
    - devenv
  only:
    - tags
  script:
    - trigger -h http://gitlab.fpt.net -u /api/v4/projects -a rd6ApchjALgm-d7uzkCA -p deb638fe6d902c968a4e8ca443ca60 -o 0 -e STAGE="build" -e DOCKER_TAG=$CI_COMMIT_TAG -t main 2628

prod-deploy:
  stage: deploy
  tags:
    - devenv
  script:
    - trigger -h http://gitlab.fpt.net -u /api/v4/projects -a rd6ApchjALgm-d7uzkCA -p deb638fe6d902c968a4e8ca443ca60 -e STAGE="deploy" -e DOCKER_TAG=$CI_COMMIT_TAG -t main 2628
  only:
    refs:
      - tags
